---
- name: install elasticsearch and kibana
  hosts: elasticsearch
  become: yes
  become_method: sudo
  remote_user: operation

  roles:
    - java
    - elasticsearch
    #- { role: nginx, user_type: 'nginx', tags: 'jenkins' }




