---
- name: install jenkins
  hosts: ci-servers
  become: yes
  become_method: sudo
  remote_user: operation

  roles:
    - java
    - jenkins
    #- { role: nginx, user_type: 'nginx', tags: 'jenkins' }




