---
- hosts: databases
  remote_user: operation

  tasks:
  - name: ensure mysql is at the latest version
    yum: name=mysql-server state=latest

  - name: ensure that mysql is started
    service: name=mysqld state=started